// ============================================================
// CYNA — DESIGN SYSTEM 2026
// Clean Light · Brand Blue #0d3d6e
// ============================================================

export const DS = {
  // ── Cartes ──────────────────────────────────────────────────
  card: {
    background: 'var(--ds-card-bg)',
    backdropFilter: 'var(--ds-card-blur)',
    WebkitBackdropFilter: 'var(--ds-card-blur)',
    padding: 'var(--ds-card-padding, 20px)',
    borderRadius: '14px',
    marginBottom: 'var(--ds-card-mb, 20px)',
    boxShadow: 'var(--ds-card-shadow)',
    border: '1px solid var(--ds-card-border)',
    position: 'relative',
  },
  cardCompact: {
    background: 'var(--ds-card-compact-bg)',
    backdropFilter: 'var(--ds-card-blur)',
    WebkitBackdropFilter: 'var(--ds-card-blur)',
    padding: 'var(--ds-card-compact-padding, 16px 18px)',
    borderRadius: '12px',
    marginBottom: 'var(--ds-card-compact-mb, 16px)',
    boxShadow: 'var(--ds-card-compact-shadow)',
    border: '1px solid var(--ds-card-compact-border)',
    position: 'relative',
  },
  cardInset: {
    background: 'var(--ds-card-inset-bg)',
    borderRadius: '10px',
    padding: 'var(--ds-card-inset-padding, 14px 16px)',
    border: '1px solid var(--ds-card-inset-border)',
    boxShadow: 'var(--ds-card-inset-shadow)',
  },

  // ── Boutons ─────────────────────────────────────────────────
  // Primary — CYNA bleu profond
  btnPrimary: {
    background: '#0d3d6e',
    color: '#fff',
    border: 'none',
    borderRadius: '9px',
    padding: '9px 16px',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    boxShadow: '0 2px 8px rgba(13,61,110,0.28)',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
    transition: 'background 0.14s ease, box-shadow 0.14s ease',
  },
  // Success — vert
  btnSuccess: {
    background: 'linear-gradient(135deg, #059669 0%, #10b981 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '9px',
    padding: '9px 16px',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    boxShadow: '0 2px 8px rgba(16,185,129,0.28)',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
  },
  // Danger — rouge subtil
  btnDanger: {
    background: 'var(--red-bg)',
    color: '#ef4444',
    border: '1px solid rgba(239,68,68,0.28)',
    borderRadius: '9px',
    padding: '8px 14px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
  },
  // Ghost — blanc avec bordure
  btnGhost: {
    background: 'var(--ds-btn-ghost-bg)',
    color: 'var(--text-secondary)',
    border: '1px solid var(--ds-btn-ghost-border)',
    borderRadius: '9px',
    padding: '8px 14px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
  },
  // Warning — ambre
  btnWarning: {
    background: 'var(--orange-bg)',
    color: '#f59e0b',
    border: '1px solid rgba(245,158,11,0.28)',
    borderRadius: '9px',
    padding: '8px 14px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
  },
  // Icon button — petits boutons action (tables, topbar)
  iconBtn: {
    background: 'var(--bg-hover)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    width: '36px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: 'var(--text-muted)',
    transition: 'background 0.12s ease, border-color 0.12s ease',
  },
  // Icon button topbar
  btnIconWhite: {
    width: '36px',
    height: '36px',
    borderRadius: '9px',
    background: 'transparent',
    border: '1px solid transparent',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--text-muted)',
    transition: 'background 0.12s ease, border-color 0.12s ease',
  },

  // ── Inputs ──────────────────────────────────────────────────
  input: {
    width: '100%',
    padding: '9px 13px',
    borderRadius: '9px',
    border: '1px solid var(--ds-input-border)',
    background: 'var(--ds-input-bg)',
    color: 'var(--text-primary)',
    fontSize: '13.5px',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    outline: 'none',
    transition: 'border-color 0.15s ease, box-shadow 0.15s ease',
  },
  label: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    color: 'var(--text-muted)',
    marginBottom: '6px',
  },

  // ── Tables ──────────────────────────────────────────────────
  th: {
    padding: '11px 14px',
    fontSize: '10.5px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.7px',
    color: 'var(--text-muted)',
    background: 'var(--ds-th-bg)',
    borderBottom: '1px solid var(--ds-th-border)',
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  td: {
    padding: '13px 14px',
    fontSize: '13px',
    color: 'var(--text-primary)',
    fontWeight: 500,
    borderBottom: '1px solid var(--ds-td-border)',
    whiteSpace: 'nowrap',
  },

  // ── Sections ────────────────────────────────────────────────
  sectionLabel: {
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '1.2px',
    color: 'var(--ds-section-label-color)',
    marginBottom: '14px',
    paddingBottom: '10px',
    borderBottom: '1px solid var(--ds-section-label-border)',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },

  // ── Brand CYNA ──────────────────────────────────────────────
  brand: {
    primary:      '#0d3d6e',
    primaryDeep:  '#082d52',
    secondary:    '#1557a0',
    soft:         '#e8f0f9',
    tint:         '#f0f6ff',
    gradient:     'linear-gradient(135deg, #0d3d6e 0%, #1557a0 100%)',
    gradientDeep: 'linear-gradient(135deg, #082d52 0%, #0d3d6e 100%)',
  },

  // ── KPI Cards ───────────────────────────────────────────────
  kpi: {
    blue:   { gradient: 'linear-gradient(135deg, #0d3d6e 0%, #1557a0 100%)', glow: 'rgba(13,61,110,0.28)' },
    green:  { gradient: 'linear-gradient(135deg, #047857 0%, #10b981 100%)', glow: 'rgba(16,185,129,0.28)' },
    amber:  { gradient: 'linear-gradient(135deg, #b45309 0%, #f59e0b 100%)', glow: 'rgba(245,158,11,0.28)' },
    purple: { gradient: 'linear-gradient(135deg, #5b21b6 0%, #7c3aed 100%)', glow: 'rgba(124,58,237,0.28)' },
    red:    { gradient: 'linear-gradient(135deg, #b91c1c 0%, #ef4444 100%)', glow: 'rgba(239,68,68,0.28)' },
  },

  // ── Badges sémantiques ───────────────────────────────────────
  badges: {
    success : { bg: '#d1fae5', color: '#047857' },
    warning : { bg: '#fef3c7', color: '#b45309' },
    danger  : { bg: '#fee2e2', color: '#b91c1c' },
    info    : { bg: '#dbeafe', color: '#1e40af' },
    neutral : { bg: '#f1f5f9', color: '#475569' },
    purple  : { bg: '#ede9fe', color: '#5b21b6' },
    brand   : { bg: '#e8f0f9', color: '#0d3d6e' },
  },

  // ── Statuts badges ───────────────────────────────────────────
  statuts: {
    'En cours':   { bg: '#dbeafe', color: '#1e40af' },
    'Terminé':    { bg: '#d1fae5', color: '#047857' },
    'Planifié':   { bg: '#e8f0f9', color: '#0d3d6e' },
    'Suspendu':   { bg: '#fee2e2', color: '#b91c1c' },
    'Facturé':    { bg: '#ede9fe', color: '#5b21b6' },
    'Brouillon':  { bg: '#f1f5f9', color: '#475569' },
    'Envoyé':     { bg: '#dbeafe', color: '#1e40af' },
    'Accepté':    { bg: '#d1fae5', color: '#047857' },
    'Refusé':     { bg: '#fee2e2', color: '#b91c1c' },
    'Payée':      { bg: '#d1fae5', color: '#047857' },
    'En retard':  { bg: '#fee2e2', color: '#b91c1c' },
    'En attente': { bg: '#fef3c7', color: '#b45309' },
    'Partielle':  { bg: '#fef3c7', color: '#b45309' },
    // Alias minuscules
    'en cours':   { bg: '#dbeafe', color: '#1e40af' },
    'terminé':    { bg: '#d1fae5', color: '#047857' },
    'planifié':   { bg: '#e8f0f9', color: '#0d3d6e' },
    'suspendu':   { bg: '#fee2e2', color: '#b91c1c' },
    'facturé':    { bg: '#ede9fe', color: '#5b21b6' },
    'brouillon':  { bg: '#f1f5f9', color: '#475569' },
    'envoyé':     { bg: '#dbeafe', color: '#1e40af' },
    'accepté':    { bg: '#d1fae5', color: '#047857' },
    'refusé':     { bg: '#fee2e2', color: '#b91c1c' },
    'payée':      { bg: '#d1fae5', color: '#047857' },
    'en retard':  { bg: '#fee2e2', color: '#b91c1c' },
    'en attente': { bg: '#fef3c7', color: '#b45309' },
    'partielle':  { bg: '#fef3c7', color: '#b45309' },
  },

  // ── Palette complète ─────────────────────────────────────────
  colors: {
    textPrimary:   '#0d1b2e',
    textSecondary: '#4a5568',
    textMuted:     '#7c8fa1',
    textFaint:     '#a8b8c8',
    bgApp:         '#f0f4f8',
    bgCard:        '#ffffff',
    border:        '#dce4ef',
    borderLight:   '#e8ecf2',
    activeNavBg:   '#e8f0f9',
    activeNavText: '#0d3d6e',
    brand:         '#0d3d6e',
    brandMid:      '#1557a0',
    brandLight:    '#2979d0',
    green:         '#10b981',
    greenDark:     '#047857',
    amber:         '#f59e0b',
    amberDark:     '#b45309',
    purple:        '#7c3aed',
    purpleDark:    '#5b21b6',
    red:           '#ef4444',
    redDark:       '#b91c1c',
  },
};

// ── Helpers statuts ─────────────────────────────────────────────
const _lookupStatut = (s) => DS.statuts[s] || DS.statuts[s?.trim().toLowerCase()] || null;
export const couleurStatut = (s) => _lookupStatut(s)?.color || '#0d3d6e';
export const badgeStatut   = (s) => _lookupStatut(s) || { bg: '#f1f5f9', color: '#475569' };
