// ============================================================
// CYNA — DESIGN SYSTEM TOKENS (styles partagés)
// Utilise des CSS variables pour s'adapter au thème light/dark.
// ============================================================

export const DS = {
  // ── Cartes ──────────────────────────────────────────────────
  card: {
    background: 'var(--ds-card-bg)',
    backdropFilter: 'var(--ds-card-blur)',
    WebkitBackdropFilter: 'var(--ds-card-blur)',
    padding: '24px',
    borderRadius: '16px',
    marginBottom: '24px',
    boxShadow: 'var(--ds-card-shadow)',
    border: '1px solid var(--ds-card-border)',
    position: 'relative',
  },
  cardCompact: {
    background: 'var(--ds-card-compact-bg)',
    backdropFilter: 'var(--ds-card-blur)',
    WebkitBackdropFilter: 'var(--ds-card-blur)',
    padding: '16px 20px',
    borderRadius: '14px',
    marginBottom: '16px',
    boxShadow: 'var(--ds-card-compact-shadow)',
    border: '1px solid var(--ds-card-compact-border)',
    position: 'relative',
  },
  cardInset: {
    background: 'var(--ds-card-inset-bg)',
    borderRadius: '12px',
    padding: '16px 18px',
    border: '1px solid var(--ds-card-inset-border)',
    boxShadow: 'var(--ds-card-inset-shadow)',
  },

  // ── Boutons ─────────────────────────────────────────────────
  btnPrimary: {
    background: 'linear-gradient(135deg, #3b82f6 0%, #6366f1 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    padding: '9px 18px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    boxShadow: '0 4px 14px rgba(59,130,246,0.35), inset 0 1px 0 rgba(255,255,255,0.15)',
    fontFamily: 'Inter, sans-serif',
    whiteSpace: 'nowrap',
  },
  btnSuccess: {
    background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    padding: '9px 18px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    boxShadow: '0 4px 14px rgba(16,185,129,0.35), inset 0 1px 0 rgba(255,255,255,0.15)',
    fontFamily: 'Inter, sans-serif',
    whiteSpace: 'nowrap',
  },
  btnDanger: {
    background: 'var(--red-bg)',
    color: '#ef4444',
    border: '1px solid rgba(239,68,68,0.3)',
    borderRadius: '10px',
    padding: '8px 16px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontFamily: 'Inter, sans-serif',
    whiteSpace: 'nowrap',
  },
  btnGhost: {
    background: 'var(--ds-btn-ghost-bg)',
    color: 'var(--text-secondary)',
    border: '1px solid var(--ds-btn-ghost-border)',
    borderRadius: '10px',
    padding: '8px 16px',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    fontFamily: 'Inter, sans-serif',
    whiteSpace: 'nowrap',
  },
  btnWarning: {
    background: 'var(--orange-bg)',
    color: '#f59e0b',
    border: '1px solid rgba(245,158,11,0.3)',
    borderRadius: '10px',
    padding: '8px 16px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontFamily: 'Inter, sans-serif',
    whiteSpace: 'nowrap',
  },

  // ── Inputs ──────────────────────────────────────────────────
  input: {
    width: '100%',
    padding: '9px 13px',
    borderRadius: '10px',
    border: '1px solid var(--ds-input-border)',
    background: 'var(--ds-input-bg)',
    color: 'var(--text-primary)',
    fontSize: '14px',
    fontFamily: 'Inter, sans-serif',
    boxSizing: 'border-box',
    outline: 'none',
  },
  label: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    color: 'var(--text-secondary)',
    marginBottom: '6px',
  },

  // ── Tables ──────────────────────────────────────────────────
  th: {
    padding: '10px 16px',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    color: 'var(--text-secondary)',
    background: 'var(--ds-th-bg)',
    borderBottom: '1px solid var(--ds-th-border)',
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  td: {
    padding: '12px 16px',
    fontSize: '14px',
    color: 'var(--text-primary)',
    fontWeight: 500,
    borderBottom: '1px solid var(--ds-td-border)',
  },

  // ── Sections ────────────────────────────────────────────────
  sectionLabel: {
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '1.4px',
    color: 'var(--ds-section-label-color)',
    marginBottom: '14px',
    paddingBottom: '10px',
    borderBottom: '1px solid var(--ds-section-label-border)',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
};
